name: Reusable Workflow Analyze Code

on:
  workflow_call:

jobs:
  analyze:
    name: "[Analyze Code]"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: "[Restore node modules]"
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-nodemodules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-nodemodules-

      - name: "[Run lint]"
        run: yarn run lint

      - name: "[Run prettier-check]"
        uses: creyD/prettier_action@v4.2
        with:
          prettier_options: --check src/**/*.{ts,js,css,html}
